# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://jiwu6498.github.io'
baseurl: 'jiwu6498.github.io'
# title: 'My website'
# description: 'This is my new website'
# permalink: pretty


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/

# # Footer nav
# navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    # feature_image: "https://picsum.photos/2560/600?image=866" 
