# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://jiwu6498.github.io'
baseurl: ''
# title: 'My website'
# description: 'This is my new website'
# permalink: pretty

# Add front matter to static files
defaults:
  - scope:
      path: "images"
    values:
      image: true
      
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      js: true

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/
- title: Posts
  url: /blog/posts/

# # Footer nav
# navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
 

