# Set theme
remote_theme:daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
# url: 'https://mydomain.com'
baseurl: 'jiwu6498.github.io'
# title: 'My website'
# description: 'This is my new website'
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
# navigation_header:
- title: Home
  url: /
- title: Projects
  url: /projects/
- title: Blog
  url: /blog/

# Collections
collections:
  posts:
    title: Posts
    output: true
    # description: "My thoughts and ideas"
   
